import type { AgendaItem, AgendaProvider } from "../types.ts";

const sampleAgendaItems: AgendaItem[] = [
  {
    id: "sample-1",
    providerId: "sample",
    state: "DONE",
    priority: "B",
    title: "Review weekend capture",
    day: 1,
    time: "08:30",
    tags: ["inbox"],
  },
  {
    id: "sample-2",
    providerId: "sample",
    state: "TODO",
    priority: "A",
    title: "Draft week plan",
    day: 1,
    time: "10:00",
    tags: ["plan"],
  },
  {
    id: "sample-3",
    providerId: "sample",
    state: "TODO",
    priority: "C",
    title: "Clean up PKM notes",
    day: 1,
    time: "15:00",
    tags: ["notes"],
  },
  {
    id: "sample-4",
    providerId: "sample",
    state: "TODO",
    priority: "A",
    title: "Review overnight notes",
    day: 2,
    time: "08:15",
    tags: ["inbox"],
  },
  {
    id: "sample-5",
    providerId: "sample",
    state: "WAIT",
    priority: "B",
    title: "Check renderer API questions",
    day: 2,
    time: "10:10",
    tags: ["pi"],
  },
  {
    id: "sample-6",
    providerId: "sample",
    state: "TODO",
    priority: "B",
    title: "Prototype source block results",
    day: 2,
    time: "13:20",
    tags: ["blocks"],
  },
  {
    id: "sample-7",
    providerId: "sample",
    state: "TODO",
    priority: "A",
    title: "Sketch rich-doc block model",
    day: 3,
    time: "09:30",
    tags: ["pi", "design"],
  },
  {
    id: "sample-8",
    providerId: "sample",
    state: "TODO",
    priority: "B",
    title: "Try collapsible heading component",
    day: 3,
    time: "11:00",
    tags: ["tui"],
  },
  {
    id: "sample-9",
    providerId: "sample",
    state: "TODO",
    priority: "B",
    title: "Test footer agenda surface",
    day: 3,
    time: "13:00",
    tags: ["footer"],
  },
  {
    id: "sample-10",
    providerId: "sample",
    state: "WAIT",
    priority: "C",
    title: "Compare HTML export paths",
    day: 3,
    time: "14:30",
    tags: ["export"],
  },
  {
    id: "sample-11",
    providerId: "sample",
    state: "TODO",
    priority: "A",
    title: "Write org-ish parser notes",
    day: 3,
    time: "15:20",
    tags: ["parser"],
  },
  {
    id: "sample-12",
    providerId: "sample",
    state: "DONE",
    priority: "B",
    title: "Create PKM agenda extension",
    day: 3,
    time: "17:00",
    tags: ["pkm"],
  },
  {
    id: "sample-13",
    providerId: "sample",
    state: "TODO",
    priority: "C",
    title: "Collect agenda UX learnings",
    day: 3,
    time: "18:10",
    tags: ["notes"],
  },
  {
    id: "sample-14",
    providerId: "sample",
    state: "TODO",
    priority: "A",
    title: "Render block formulas in rich doc",
    day: 4,
    time: "09:00",
    tags: ["latex"],
  },
  {
    id: "sample-15",
    providerId: "sample",
    state: "WAIT",
    priority: "B",
    title: "Ask about native rich blocks",
    day: 4,
    time: "11:30",
    tags: ["pi"],
  },
  {
    id: "sample-16",
    providerId: "sample",
    state: "TODO",
    priority: "C",
    title: "Try graph block component",
    day: 4,
    time: "16:00",
    tags: ["charts"],
  },
  {
    id: "sample-17",
    providerId: "sample",
    state: "TODO",
    priority: "B",
    title: "Agenda polish pass",
    day: 5,
    time: "10:00",
    tags: ["agenda"],
  },
  {
    id: "sample-18",
    providerId: "sample",
    state: "TODO",
    priority: "C",
    title: "Export experiment checklist",
    day: 5,
    time: "14:00",
    tags: ["export"],
  },
  {
    id: "sample-19",
    providerId: "sample",
    state: "TODO",
    priority: "C",
    title: "Weekly review",
    day: 6,
    time: "11:00",
    tags: ["review"],
  },
  {
    id: "sample-20",
    providerId: "sample",
    state: "WAIT",
    priority: "C",
    title: "Sunday idea parking lot",
    day: 7,
    time: "16:00",
    tags: ["someday"],
  },
];

export const sampleAgendaProvider: AgendaProvider = {
  id: "sample",
  label: "sample",
  async listAgenda() {
    return sampleAgendaItems.map((item) => ({ ...item, tags: [...item.tags] }));
  },
  async markDone(item) {
    const match = sampleAgendaItems.find((candidate) => candidate.id === item.id);
    if (!match) return { ok: false, message: "Sample agenda item not found" };
    match.state = "DONE";
    return { ok: true, message: `Marked done: ${match.title}` };
  },
};
